package app.exceptions;

public enum CityExcCode {
    CITY_NOT_FOUND,
    CAR_CODE_IN_USE,
    CITY_SAVING_ERROR,
    CITY_DELETION_ERROR,
    DATABASE_CONN_FAILED,
    MINIO_CONN_FAILED,
    DATABASE_DOWN,
    MINIO_DOWN,
    COORDS_NOT_FOUND,
    COORDS_SAVING_ERROR,
    COORDS_DELETION_ERROR,
    HUMAN_NOT_FOUND,
    HUMAN_SAVING_ERROR,
    HUMAN_DELETION_ERROR,
    NOT_A_USER,
    UNAUTHORIZED_REQUEST,
    REGISTRATION_FAILED,
    PROMOTION_FAILED,
    DATABASE_ERROR,
    LOGIN_FAILED
}
